applicationName: "plants-application-form-service"
versionNumber: "${APPLICATION_FORM_SERVICE_VERSION}"

server:
  applicationConnectors:
  - type: http
    port: !!int ${APPLICATION_FORM_SERVICE_PORT}
    maxRequestHeaderSize: 128KiB
  adminConnectors:
  - type: http
    port: 4561

database:
  driverClass: com.microsoft.sqlserver.jdbc.SQLServerDriver
  user: ${APPLICATION_FORM_SERVICE_DB_USER}
  password: ${APPLICATION_FORM_SERVICE_DB_PASSWORD}
  url: "jdbc:sqlserver://${APPLICATION_FORM_SERVICE_DB_HOST}:${APPLICATION_FORM_SERVICE_DB_PORT};databaseName=${APPLICATION_FORM_SERVICE_DB_NAME};encrypt=true;trustServerCertificate=true"
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: ${APPLICATION_FORM_SERVICE_DB_MIN_SIZE}
  maxSize: ${APPLICATION_FORM_SERVICE_DB_MAX_SIZE}
  checkConnectionWhileIdle: true
  evictionInterval: 10s
  minIdleTime: 1 minute

# Application Form to Case Management calls do not retry, this is application submission to dynamics
caseManagementServiceClient:
  connectionTimeout: 1s
  timeout: 100s

caseManagementService:
  baseUri: "${CASE_MANAGEMENT_SERVICE_SCHEME}://${CASE_MANAGEMENT_SERVICE_HOST}:${CASE_MANAGEMENT_SERVICE_PORT}"

formConfigurationServiceClient:
  connectionTimeout: ${FORM_CONFIGURATION_SERVICE_CONNECTION_TIMEOUT}
  timeout: ${FORM_CONFIGURATION_SERVICE_TIMEOUT}

formConfigurationService:
  baseUri: "${FORM_CONFIGURATION_SERVICE_SCHEME}://${FORM_CONFIGURATION_SERVICE_HOST}:${FORM_CONFIGURATION_SERVICE_PORT}"
  retryWait: ${FORM_CONFIGURATION_SERVICE_RETRY_WAIT}

certificateServiceClient:
  connectionTimeout: ${CERTIFICATE_SERVICE_CONNECTION_TIMEOUT}
  timeout: ${CERTIFICATE_SERVICE_TIMEOUT}

certificateService:
  baseUri: "${CERTIFICATE_SERVICE_SCHEME}://${CERTIFICATE_SERVICE_HOST}:${CERTIFICATE_SERVICE_PORT}"
  retryWait: ${CERTIFICATE_SERVICE_RETRY_WAIT}

logging:
  level: "${APPLICATION_FORM_SERVICE_LOGGING_LEVEL}"
  appenders:
  - type: application-insights
  - type: console
    timeZone: UTC
    logFormat: "%-5level [%date{ISO8601,UTC}] %mdc{defra-exports-correlation-id} %mdc{defra-exports-correlation-count} %logger{50}: %message%n%rootException"

basicAuthenticationCredentials:
  password: "${APPLICATION_FORM_SERVICE_BASIC_AUTH_PASSWORD}"

eventHubConfiguration:
  eventHubNamespace: "${EVENT_HUB_NAMESPACE}"
  eventHubName: "${EVENT_HUB_NAME}"
  eventHubSharedAccessKeyName: "${EVENT_HUB_KEY_NAME}"
  eventHubSharedAccessKey: "${EVENT_HUB_KEY_VALUE}"
  numberOfThreads: "${EVENT_HUB_CLIENT_THREAD_COUNT}"
  environmentAbbreviation: "${ENVIRONMENT_ABBREVIATION}"

swagger:
  resourcePackage: uk.gov.defra.plants.applicationform.resource
  schemes:
  - "${APPLICATION_FORM_SERVICE_SCHEME}"

jwtKey: ${JWT_DER}
internalSymmetricalKey: "${INTERNAL_SYMMETRICAL_KEY}"

automatedTestsActive: "${RUN_AUTOMATION_TESTS}"